# Generated by Django 4.2.1 on 2023-09-13 06:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Json',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('body', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=100)),
                ('body', models.TextField(default='')),
                ('slug', models.SlugField(default='', max_length=100, unique_for_date='publish')),
                ('publish', models.DateTimeField(default=django.utils.timezone.now)),
                ('image', models.ImageField(default='', upload_to='static/img')),
                ('uptions', models.CharField(choices=[('private', 'Private'), ('public', 'Public')], default='public', max_length=10)),
            ],
            options={
                'ordering': ('-publish',),
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='  ', max_length=100)),
                ('email', models.CharField(default=' ', max_length=222)),
                ('password', models.CharField(default='', max_length=18)),
                ('confirm_password', models.CharField(default='', max_length=18)),
                ('register_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
